[build]
    publish = "out"
[build.processing.css]
    bundle = false
    minify = false
[build.processing.js]
    bundle = false
    minify = false
[build.processing.html]
    pretty_urls = true
[build.processing.images]
    compress = true
[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
[[headers]]
    for = "/static/*"
    [headers.values]
        cache-control = '''
        public,
        max-age=31536000,
        immutable'''
